import io
import sys
import tempfile
import tomllib
import unittest
from contextlib import redirect_stderr
from datetime import date, time
from pathlib import Path
from unittest.mock import patch
from zoneinfo import ZoneInfo

from icalendar import Calendar

from calendargen.cli import main
from calendargen.schedule import (
    TEMPLATE,
    Course,
    DayOverride,
    Schedule,
    TimeSlot,
    generate_calendar,
    load_schedule,
)

SCHEDULE = """term_start = 2026-05-04
term_end = 2026-05-11
excluded_dates = [2026-05-05]

[time_slots]
"period 1" = { start = "08:45", end = "10:15" }
"lunch" = { start = "12:00", end = "13:15" }
"2" = { start = "13:15", end = "14:45" }

[[courses]]
title = "Monday class"
description = "Professor Smith"
weekday = "mon"
time_slot = "period 1"
location = "A101"

[[courses]]
title = "Tuesday class"
weekday = "tue"
time_slot = "lunch"

[[courses]]
title = "Wednesday class"
weekday = "wed"
time_slot = "2"

[[day_overrides]]
date = 2026-05-06
use_weekday = "mon"
"""


class CalendarTests(unittest.TestCase):
    def setUp(self):
        self.temporary = tempfile.TemporaryDirectory()
        self.addCleanup(self.temporary.cleanup)
        self.directory = Path(self.temporary.name)
        self.toml_path = self.directory / "calendar.toml"
        self.toml_path.write_text(SCHEDULE, encoding="utf-8")

    def test_template_is_valid_toml(self):
        data = tomllib.loads(TEMPLATE)
        self.assertEqual(
            data["description_footer"], "Generated by CalendarGen (Fall 2026)"
        )
        self.assertEqual(data["time_slots"]["period 1"]["start"], "08:45")
        self.assertIn("lunch", data["time_slots"])
        self.assertEqual(data["courses"][0]["description"], "Professor Tsujimoto")
        self.assertEqual(
            data["day_overrides"][0]["all_day_event_title"],
            "swapped to Monday schedule",
        )
        self.toml_path.write_text(TEMPLATE, encoding="utf-8")
        load_schedule(self.toml_path)

    def test_schedule_uses_domain_objects_and_selects_courses(self):
        schedule = load_schedule(self.toml_path)
        self.assertIsInstance(schedule, Schedule)
        self.assertIsInstance(schedule.time_slots["period 1"], TimeSlot)
        self.assertIsInstance(schedule.courses[0], Course)
        self.assertIs(schedule.courses[0].time_slot, schedule.time_slots["period 1"])
        self.assertIsInstance(schedule.overrides[date(2026, 5, 6)], DayOverride)
        self.assertEqual(schedule.weekday_on(date(2026, 5, 6)), 0)
        self.assertEqual(
            schedule.courses_on(date(2026, 5, 6)), [(0, schedule.courses[0])]
        )
        self.assertEqual(
            schedule.courses_on(date(2026, 5, 4)), [(0, schedule.courses[0])]
        )
        self.assertEqual(schedule.courses_on(date(2026, 5, 5)), [])
        self.assertEqual(schedule.courses_on(date(2026, 5, 12)), [])

    @patch("calendargen.schedule.get_localzone", return_value=ZoneInfo("Asia/Tokyo"))
    def test_calendar_dates_overrides_and_timezone(self, _zone):
        calendar = Calendar.from_ical(
            generate_calendar(load_schedule(self.toml_path), self.toml_path)
        )
        events = list(calendar.walk("VEVENT"))
        self.assertEqual(len(events), 3)
        self.assertEqual(
            [event.decoded("DTSTART").date() for event in events],
            [date(2026, 5, 4), date(2026, 5, 6), date(2026, 5, 11)],
        )
        self.assertEqual(
            [str(event["SUMMARY"]) for event in events], ["Monday class"] * 3
        )
        self.assertEqual(events[1].decoded("DTSTART").time(), time(8, 45))
        self.assertEqual(events[1].decoded("DTEND").time(), time(10, 15))
        self.assertEqual(
            events[1].decoded("DTSTART").utcoffset().total_seconds(), 9 * 3600
        )
        self.assertEqual(len(list(calendar.walk("VTIMEZONE"))), 1)
        self.assertEqual(events[0]["LOCATION"], "A101")
        self.assertEqual(str(events[0]["DESCRIPTION"]), "Professor Smith")
        self.assertEqual(
            [event["UID"] for event in events],
            [
                event["UID"]
                for event in Calendar.from_ical(
                    generate_calendar(load_schedule(self.toml_path), self.toml_path)
                ).walk("VEVENT")
            ],
        )

    def test_excluded_date_and_override_collision_is_an_error(self):
        self.toml_path.write_text(
            SCHEDULE.replace(
                "excluded_dates = [2026-05-05]", "excluded_dates = [2026-05-06]"
            ),
            encoding="utf-8",
        )
        with self.assertRaisesRegex(
            ValueError, "both excluded_dates and day_overrides"
        ):
            load_schedule(self.toml_path)

    def test_unknown_fields_identify_their_location(self):
        cases = (
            (
                "schedule",
                "term_strat",
                SCHEDULE.replace(
                    "term_start = 2026-05-04",
                    "term_start = 2026-05-04\nterm_strat = 2026-05-04",
                ),
            ),
            (
                "time slot 'period 1'",
                "star",
                SCHEDULE.replace('start = "08:45"', 'star = "08:45"'),
            ),
            (
                "course 1",
                "titel",
                SCHEDULE.replace('title = "Monday class"', 'titel = "Monday class"'),
            ),
            (
                "day_overrides item 1",
                "use_weekdays",
                SCHEDULE.replace('use_weekday = "mon"', 'use_weekdays = "mon"'),
            ),
        )
        for context, field, contents in cases:
            with self.subTest(context=context):
                self.toml_path.write_text(contents, encoding="utf-8")
                with self.assertRaises(ValueError) as raised:
                    load_schedule(self.toml_path)
                self.assertIn(context, str(raised.exception))
                self.assertIn(field, str(raised.exception))

    def test_excluded_dates_must_be_within_term_including_boundaries(self):
        for day in ("2026-05-03", "2026-05-12"):
            with self.subTest(day=day):
                self.toml_path.write_text(
                    SCHEDULE.replace("2026-05-05]", f"{day}]"),
                    encoding="utf-8",
                )
                with self.assertRaises(ValueError) as raised:
                    load_schedule(self.toml_path)
                self.assertIn(day, str(raised.exception))
                self.assertIn("2026-05-04 to 2026-05-11", str(raised.exception))

        self.toml_path.write_text(
            SCHEDULE.replace("2026-05-05]", "2026-05-04, 2026-05-11]"),
            encoding="utf-8",
        )
        self.assertEqual(
            load_schedule(self.toml_path).excluded_dates,
            frozenset((date(2026, 5, 4), date(2026, 5, 11))),
        )

    def test_day_overrides_dates_must_be_within_term_including_boundaries(self):
        for day in ("2026-05-03", "2026-05-12"):
            with self.subTest(day=day):
                self.toml_path.write_text(
                    SCHEDULE.replace("date = 2026-05-06", f"date = {day}"),
                    encoding="utf-8",
                )
                with self.assertRaises(ValueError) as raised:
                    load_schedule(self.toml_path)
                self.assertIn(day, str(raised.exception))
                self.assertIn("2026-05-04 to 2026-05-11", str(raised.exception))

        for day in ("2026-05-04", "2026-05-11"):
            with self.subTest(day=day):
                self.toml_path.write_text(
                    SCHEDULE.replace("date = 2026-05-06", f"date = {day}"),
                    encoding="utf-8",
                )
                self.assertIn(
                    date.fromisoformat(day), load_schedule(self.toml_path).overrides
                )

    @patch("calendargen.schedule.get_localzone", return_value=ZoneInfo("Asia/Tokyo"))
    def test_all_day_event_title_adds_an_event_with_or_without_a_course(self, _zone):
        for weekday, event_count in (("mon", 4), ("sun", 3)):
            with self.subTest(weekday=weekday):
                self.toml_path.write_text(
                    SCHEDULE.replace(
                        'use_weekday = "mon"',
                        f'use_weekday = "{weekday}"\nall_day_event_title = "Schedule change"',
                    ),
                    encoding="utf-8",
                )
                schedule = load_schedule(self.toml_path)
                events = list(
                    Calendar.from_ical(
                        generate_calendar(schedule, self.toml_path)
                    ).walk("VEVENT")
                )
                annotations = [
                    event
                    for event in events
                    if str(event["SUMMARY"]) == "Schedule change"
                ]
                self.assertEqual(len(annotations), 1)
                annotation = annotations[0]
                self.assertEqual(annotation.decoded("DTSTART"), date(2026, 5, 6))
                self.assertEqual(annotation.decoded("DTEND"), date(2026, 5, 7))
                self.assertEqual(len(events), event_count)
                self.assertEqual(
                    len({str(event["UID"]) for event in events}), len(events)
                )
                regenerated = Calendar.from_ical(
                    generate_calendar(schedule, self.toml_path)
                )
                self.assertEqual(
                    str(annotation["UID"]),
                    str(
                        next(
                            event
                            for event in regenerated.walk("VEVENT")
                            if str(event["SUMMARY"]) == "Schedule change"
                        )["UID"]
                    ),
                )

    def test_blank_or_missing_all_day_event_title_adds_no_event(self):
        for field in ("", 'all_day_event_title = ""', 'all_day_event_title = "   "'):
            with self.subTest(field=field):
                self.toml_path.write_text(SCHEDULE + field + "\n", encoding="utf-8")
                events = Calendar.from_ical(
                    generate_calendar(load_schedule(self.toml_path), self.toml_path)
                )
                self.assertEqual(len(list(events.walk("VEVENT"))), 3)

    def test_all_day_event_title_must_be_text(self):
        self.toml_path.write_text(
            SCHEDULE + "all_day_event_title = 42\n", encoding="utf-8"
        )
        with self.assertRaisesRegex(ValueError, "all_day_event_title must be a string"):
            load_schedule(self.toml_path)

    def test_named_and_numeric_time_slots(self):
        self.toml_path.write_text(
            SCHEDULE.replace(
                "excluded_dates = [2026-05-05]", "excluded_dates = []"
            ).replace('use_weekday = "mon"', 'use_weekday = "wed"'),
            encoding="utf-8",
        )
        calendar = Calendar.from_ical(
            generate_calendar(load_schedule(self.toml_path), self.toml_path)
        )
        events = list(calendar.walk("VEVENT"))
        starts = [event.decoded("DTSTART") for event in events]
        self.assertNotIn("DESCRIPTION", events[1])
        self.assertEqual(
            [(start.date(), start.time()) for start in starts],
            [
                (date(2026, 5, 4), time(8, 45)),
                (date(2026, 5, 5), time(12, 0)),
                (date(2026, 5, 6), time(13, 15)),
                (date(2026, 5, 11), time(8, 45)),
            ],
        )

    def test_unknown_time_slot_is_an_error(self):
        self.toml_path.write_text(
            SCHEDULE.replace('time_slot = "period 1"', 'time_slot = "unknown"', 1),
            encoding="utf-8",
        )
        with self.assertRaisesRegex(ValueError, "unknown time_slot"):
            load_schedule(self.toml_path)

    def test_description_must_be_text(self):
        self.toml_path.write_text(
            SCHEDULE.replace('description = "Professor Smith"', "description = 42"),
            encoding="utf-8",
        )
        with self.assertRaisesRegex(ValueError, "description must be a string"):
            load_schedule(self.toml_path)

    @patch("calendargen.schedule.get_localzone", return_value=ZoneInfo("Asia/Tokyo"))
    def test_description_footer_applies_to_all_generated_events(self, _zone):
        self.toml_path.write_text(
            SCHEDULE.replace(
                "excluded_dates = [2026-05-05]",
                'excluded_dates = []\ndescription_footer = "My import batch"',
            ).replace(
                'use_weekday = "mon"',
                'use_weekday = "mon"\nall_day_event_title = "Schedule change"',
            ),
            encoding="utf-8",
        )
        events = list(
            Calendar.from_ical(
                generate_calendar(load_schedule(self.toml_path), self.toml_path)
            ).walk("VEVENT")
        )
        self.assertEqual(len(events), 5)
        for event in events:
            expected = (
                "My import batch"
                if str(event["SUMMARY"]) in ("Schedule change", "Tuesday class")
                else "Professor Smith\n\nMy import batch"
            )
            self.assertEqual(str(event["DESCRIPTION"]), expected)

    def test_blank_description_footer_leaves_descriptions_unchanged(self):
        for footer in ('""', '"   "'):
            with self.subTest(footer=footer):
                self.toml_path.write_text(
                    SCHEDULE.replace(
                        "excluded_dates = [2026-05-05]",
                        f"excluded_dates = [2026-05-05]\ndescription_footer = {footer}",
                    ).replace(
                        'use_weekday = "mon"',
                        'use_weekday = "mon"\nall_day_event_title = "Schedule change"',
                    ),
                    encoding="utf-8",
                )
                events = list(
                    Calendar.from_ical(
                        generate_calendar(load_schedule(self.toml_path), self.toml_path)
                    ).walk("VEVENT")
                )
                descriptions = {
                    str(event["SUMMARY"]): event.get("DESCRIPTION") for event in events
                }
                self.assertEqual(str(descriptions["Monday class"]), "Professor Smith")
                self.assertIsNone(descriptions["Schedule change"])

    def test_description_footer_must_be_text(self):
        self.toml_path.write_text(
            SCHEDULE.replace(
                "excluded_dates = [2026-05-05]",
                "excluded_dates = [2026-05-05]\ndescription_footer = 42",
            ),
            encoding="utf-8",
        )
        with self.assertRaisesRegex(ValueError, "description_footer must be a string"):
            load_schedule(self.toml_path)

    def test_cli_init_and_gen(self):
        init_path = self.directory / "new.toml"
        ics_path = self.directory / "calendar.ics"
        with patch.object(sys, "argv", ["calendargen", "init", str(init_path)]):
            main()
        self.assertEqual(init_path.read_text(encoding="utf-8"), TEMPLATE)
        with patch.object(sys, "argv", ["calendargen", "init", str(init_path)]):
            with self.assertRaises(SystemExit), redirect_stderr(io.StringIO()):
                main()
        with patch.object(
            sys, "argv", ["calendargen", "gen", str(self.toml_path), str(ics_path)]
        ):
            main()
        self.assertEqual(
            len(list(Calendar.from_ical(ics_path.read_bytes()).walk("VEVENT"))), 3
        )

    def test_cli_validation_failure_does_not_create_or_overwrite_output(self):
        self.toml_path.write_text(
            SCHEDULE.replace('use_weekday = "mon"', 'use_weekdays = "mon"'),
            encoding="utf-8",
        )
        for existing in (False, True):
            with self.subTest(existing=existing):
                ics_path = self.directory / "calendar.ics"
                if existing:
                    ics_path.write_bytes(b"previous calendar")
                with (
                    patch.object(
                        sys,
                        "argv",
                        ["calendargen", "gen", str(self.toml_path), str(ics_path)],
                    ),
                    self.assertRaises(SystemExit) as raised,
                    redirect_stderr(io.StringIO()) as stderr,
                ):
                    main()
                self.assertEqual(raised.exception.code, 2)
                self.assertIn("use_weekdays", stderr.getvalue())
                if existing:
                    self.assertEqual(ics_path.read_bytes(), b"previous calendar")
                else:
                    self.assertFalse(ics_path.exists())


if __name__ == "__main__":
    unittest.main()
