"""Read a class schedule and turn it into an iCalendar file."""

import tomllib
from dataclasses import dataclass
from datetime import UTC, date, datetime, time, timedelta
from pathlib import Path
from uuid import NAMESPACE_URL, uuid5

from icalendar import Calendar, Event
from tzlocal import get_localzone

TEMPLATE = """term_start = 2026-10-01
term_end = 2027-01-22
excluded_dates = [2026-10-12, 2026-11-03]
description_footer = "Generated by CalendarGen (Fall 2026)"

[time_slots]
"period 1" = { start = "08:45", end = "10:15" }
"period 2" = { start = "10:30", end = "12:00" }
"lunch" = { start = "12:00", end = "13:15" }
"period 3" = { start = "13:15", end = "14:45" }
"period 4" = { start = "15:00", end = "16:30" }
"period 5" = { start = "16:45", end = "18:15" }

[[courses]]
title = "Applied Algebra"
description = "Professor Tsujimoto"
weekday = "mon"
time_slot = "period 2"
location = "Lecture Room 2, Research Building No.8"

[[courses]]
title = "Fluid Mechanics"
description = "Professor Taguchi"
weekday = "tue"
time_slot = "period 2"
location = "Lecture Room 4, Research Building No.8"

[[day_overrides]]
date = 2026-10-15
use_weekday = "mon"
all_day_event_title = "swapped to Monday schedule"

[[day_overrides]]
date = 2026-11-26
use_weekday = "tue"
all_day_event_title = "swapped to Tuesday schedule, don't forget!"
"""

WEEKDAYS = {
    name: number
    for number, name in enumerate(("mon", "tue", "wed", "thu", "fri", "sat", "sun"))
}


@dataclass(frozen=True, slots=True)
class TimeSlot:
    name: str
    start: time
    end: time


@dataclass(frozen=True, slots=True)
class Course:
    title: str
    weekday: int
    time_slot: TimeSlot
    location: str | None = None
    description: str | None = None


@dataclass(frozen=True, slots=True)
class DayOverride:
    date: date
    use_weekday: int
    all_day_event_title: str | None = None


@dataclass(frozen=True, slots=True)
class Schedule:
    start: date
    end: date
    excluded_dates: frozenset[date]
    time_slots: dict[str, TimeSlot]
    courses: tuple[Course, ...]
    overrides: dict[date, DayOverride]
    description_footer: str | None = None

    def weekday_on(self, day: date) -> int:
        override = self.overrides.get(day)
        return day.weekday() if override is None else override.use_weekday

    def courses_on(self, day: date) -> list[tuple[int, Course]]:
        if day < self.start or day > self.end or day in self.excluded_dates:
            return []
        weekday = self.weekday_on(day)
        return [
            (index, course)
            for index, course in enumerate(self.courses)
            if course.weekday == weekday
        ]


def _date(value: object, name: str) -> date:
    if type(value) is not date:
        raise ValueError(f"{name} must be a TOML date")
    return value


def _check_fields(data: dict, allowed: set[str], context: str) -> None:
    for name in data:
        if name not in allowed:
            raise ValueError(f"{context} has unknown field {name!r}")


def _check_term_date(day: date, start: date, end: date, context: str) -> None:
    if not start <= day <= end:
        raise ValueError(f"{context} {day} is outside term {start} to {end}")


def _weekday(value: object, name: str) -> int:
    if not isinstance(value, str) or value not in WEEKDAYS:
        raise ValueError(f"{name} must be one of: {', '.join(WEEKDAYS)}")
    return WEEKDAYS[value]


def _clock(value: object, name: str) -> time:
    if not isinstance(value, str):
        raise ValueError(f"{name} must be a time string such as '08:45'")
    try:
        result = time.fromisoformat(value)
    except ValueError as error:
        raise ValueError(f"{name} must be a time string such as '08:45'") from error
    if result.tzinfo is not None:
        raise ValueError(f"{name} must be a local time without an offset")
    return result


def load_schedule(path: Path) -> Schedule:
    """Load and check the fields needed to generate the calendar."""
    try:
        with path.open("rb") as file:
            data = tomllib.load(file)
    except tomllib.TOMLDecodeError as error:
        raise ValueError(f"invalid TOML in {path}: {error}") from error

    _check_fields(
        data,
        {
            "term_start",
            "term_end",
            "excluded_dates",
            "description_footer",
            "time_slots",
            "courses",
            "day_overrides",
        },
        "schedule",
    )
    start = _date(data.get("term_start"), "term_start")
    end = _date(data.get("term_end"), "term_end")
    if end < start:
        raise ValueError("term_end must not precede term_start")

    excluded_dates = data.get("excluded_dates", [])
    if not isinstance(excluded_dates, list):
        raise ValueError("excluded_dates must be a list of TOML dates")
    parsed_excluded_dates: set[date] = set()
    for value in excluded_dates:
        day = _date(value, "excluded_dates item")
        _check_term_date(day, start, end, "excluded_dates item")
        parsed_excluded_dates.add(day)
    excluded_dates = frozenset(parsed_excluded_dates)

    description_footer = data.get("description_footer")
    if description_footer is not None and not isinstance(description_footer, str):
        raise ValueError("description_footer must be a string")

    time_slots = data.get("time_slots")
    if not isinstance(time_slots, dict) or not time_slots:
        raise ValueError("time_slots must contain at least one time slot")
    parsed_time_slots: dict[str, TimeSlot] = {}
    for name, time_slot in time_slots.items():
        if not name.strip() or not isinstance(time_slot, dict):
            raise ValueError(f"invalid time slot: {name!r}")
        _check_fields(time_slot, {"start", "end"}, f"time slot {name!r}")
        begins = _clock(time_slot.get("start"), f"time slot {name!r} start")
        ends = _clock(time_slot.get("end"), f"time slot {name!r} end")
        if ends <= begins:
            raise ValueError(f"time slot {name!r} end must be after start")
        parsed_time_slots[name] = TimeSlot(name, begins, ends)

    courses = data.get("courses")
    if not isinstance(courses, list):
        raise ValueError("courses must be a list of tables")
    parsed_courses: list[Course] = []
    for index, course in enumerate(courses, start=1):
        if not isinstance(course, dict):
            raise ValueError(f"course {index} must be a table")
        _check_fields(
            course,
            {"title", "weekday", "time_slot", "location", "description"},
            f"course {index}",
        )
        title = course.get("title")
        if not isinstance(title, str) or not title.strip():
            raise ValueError(f"course {index} needs a title")
        weekday = _weekday(course.get("weekday"), f"course {index} weekday")
        time_slot = course.get("time_slot")
        if not isinstance(time_slot, str) or time_slot not in parsed_time_slots:
            raise ValueError(f"course {index} refers to an unknown time_slot")
        location = course.get("location")
        if location is not None and not isinstance(location, str):
            raise ValueError(f"course {index} location must be a string")
        description = course.get("description")
        if description is not None and not isinstance(description, str):
            raise ValueError(f"course {index} description must be a string")
        parsed_courses.append(
            Course(title, weekday, parsed_time_slots[time_slot], location, description)
        )

    overrides = data.get("day_overrides", [])
    if not isinstance(overrides, list):
        raise ValueError("day_overrides must be a list of tables")
    parsed_overrides: dict[date, DayOverride] = {}
    for index, override in enumerate(overrides, start=1):
        if not isinstance(override, dict):
            raise ValueError(f"day_overrides item {index} must be a table")
        _check_fields(
            override,
            {"date", "use_weekday", "all_day_event_title"},
            f"day_overrides item {index}",
        )
        day = _date(override.get("date"), f"day_overrides item {index} date")
        _check_term_date(day, start, end, f"day_overrides item {index} date")
        if day in excluded_dates:
            raise ValueError(f"{day} appears in both excluded_dates and day_overrides")
        if day in parsed_overrides:
            raise ValueError(f"duplicate day_overrides date: {day}")
        weekday = _weekday(
            override.get("use_weekday"), f"day_overrides item {index} use_weekday"
        )
        annotation = override.get("all_day_event_title")
        if annotation is not None and not isinstance(annotation, str):
            raise ValueError(
                f"day_overrides item {index} all_day_event_title must be a string"
            )
        parsed_overrides[day] = DayOverride(day, weekday, annotation)

    return Schedule(
        start,
        end,
        excluded_dates,
        parsed_time_slots,
        tuple(parsed_courses),
        parsed_overrides,
        description_footer,
    )


def generate_calendar(schedule: Schedule, source: Path) -> bytes:
    """Generate course occurrences and optional all-day override annotations."""
    local_zone = get_localzone()
    calendar = Calendar()
    calendar.add("prodid", "-//CalendarGen//EN")
    calendar.add("version", "2.0")

    footer = schedule.description_footer
    if footer is not None and not footer.strip():
        footer = None

    day = schedule.start
    while day <= schedule.end:
        if day not in schedule.excluded_dates:
            override = schedule.overrides.get(day)
            if (
                override is not None
                and override.all_day_event_title
                and override.all_day_event_title.strip()
            ):
                annotation = Event()
                annotation.add("summary", override.all_day_event_title)
                annotation.add("dtstart", day)
                annotation.add("dtend", day + timedelta(days=1))
                annotation.add("dtstamp", datetime.now(UTC))
                if footer is not None:
                    annotation.add("description", footer)
                # Keep the UID stable when the TOML field is renamed.
                annotation.add(
                    "uid",
                    f"{uuid5(NAMESPACE_URL, f'{source.resolve()}:allday_annotation:{day}')}@calendargen",
                )
                calendar.add_component(annotation)
            for index, course in schedule.courses_on(day):
                event = Event()
                event.add("summary", course.title)
                event.add(
                    "dtstart", datetime.combine(day, course.time_slot.start, local_zone)
                )
                event.add(
                    "dtend", datetime.combine(day, course.time_slot.end, local_zone)
                )
                event.add("dtstamp", datetime.now(UTC))
                event.add(
                    "uid",
                    f"{uuid5(NAMESPACE_URL, f'{source.resolve()}:{index}:{day}')}@calendargen",
                )
                if course.location:
                    event.add("location", course.location)
                description = course.description
                if footer is not None:
                    description = (
                        f"{description}\n\n{footer}" if description else footer
                    )
                if description is not None:
                    event.add("description", description)
                calendar.add_component(event)
        day += timedelta(days=1)

    calendar.add_missing_timezones(
        first_date=schedule.start,
        last_date=schedule.end + timedelta(days=1),
    )
    return calendar.to_ical()
